### ISSUE TITLE
Minerva should support some form of SPARQL pass-through

### ISSUE THREAD

**Issue by kltm** [geneontology/minerva#216]
To support various use cases, most importantly in the near term the ability to find just edited models in the ART, we would like to have some form of SPARQL pass-through in Minerva for editorial tools.

**Comment by balhoff** [comment]
@kltm I'm working on this now. One wrinkle I am trying to deal with: can I assume that clients won't know how to expand prefixes correctly? I am thinking that the SPARQL query parser needs to automatically use the Minerva curiehandler to expand undeclared prefixes. Besides this I have it working.

**Comment by balhoff** [comment]
I've now got the query parser handling any prefixes defined in the CurieHandler. Next up is to see if I can make the output do the reverse (compact the URIs).

**Comment by kltm** [comment]
How do you have the passthrough setup, from an API POV--this would be pumped through the current API as we described before?

**Comment by kltm** [comment]
Also, as I sometimes confuse these: https://github.com/geneontology/minerva/issues/212

**Comment by balhoff** [comment]
It's embedded in the requests API. So I have a request like this:

`curl 'http://localhost:9999/m3Batch?intention=query&requests=%5B%0A%7B%0A%22entity%22%3A%20%22meta%22%2C%0A%22operation%22%3A%20%22sparql%22%2C%0A%22arguments%22%3A%20%7B%0A%20%20%20%20%22query%22%3A%20%22CONSTRUCT%20%7B%3Fs%20%3Fp%20%3Fo%7D%20WHERE%20%7B%20GRAPH%20gomodel%3A5525a0fc00000032%20%7B%20%3Fs%20%3Fp%20%3Fo%20%7D%20%7D%22%0A%7D%0A%7D%0A%5D'`

where the requests object is:

```json
[
	{
	"entity": "meta",
	"operation": "sparql",
	"arguments": {
	    "query": "CONSTRUCT {?s ?p ?o} WHERE { GRAPH gomodel:5525a0fc00000032 { ?s ?p ?o } }"
		}
	}
]
```

Here the `gomodel` prefix doesn't need to be declared, because it is known by the CurieHandler.

**Comment by balhoff** [comment]
However I'm having a hard time getting Sesame to compact the URIs in the returned data.

**Comment by balhoff** [comment]
Aha, I'm now seeing that there is no mechanism to define prefixes in the [SPARQL Query Results JSON Format](https://www.w3.org/TR/sparql11-results-json/). Currently I'm using built in results serializers from the RDF API in Minerva (Sesame). Do we need a custom format? I.e. is it out of the question for clients to get full URIs in results?

**Comment by kltm** [comment]
That's a good question. To this point, we have considered Minerva to be the world of URLs and the clients being able to rely on CURIEs. I'd prefer to keep that if possible. What are the trade-offs in difficulty here?

**Comment by balhoff** [comment]
Not too difficult. I was just trying to embed standard JSON formats for the SPARQL results. I will need to just send it back as more custom JSON.

**Comment by kltm** [comment]
To clarify, you have no standard way to send back the SPARQL results in an already CURIEd form, so essentially you would be forced to send the results through a filter of some kind to map them over beforehand?

**Comment by balhoff** [comment]
Yep, they come back as SPARQL result objects (for SELECT) or RDF triples (for CONSTRUCT) where either way the core identifiers are IRIs. There are JSON formats for these which I can serialize to for free, but those formats don't allow CURIEs. But I can do a custom serialization where the identifiers are compacted. The data models are simple.

**Comment by kltm** [comment]
I'm not sure it matters in this case at this point, but it might be good to add experimental features to `dev` first (what is being tracked by minerva on noctua-dev.berkeleybop.org). I'll go ahead and try to get this code up somewhere now for some testing/playing.

**Comment by balhoff** [comment]
I agree—I messed that up in this case because I forgot entirely about the `dev` branch. Will stick to that in the future.

**Comment by kltm** [comment]
NP! Things all seems to be going lovely so far; I'm hoping to get a little testing in today.

**Comment by kltm** [comment]
Following: https://github.com/geneontology/minerva/issues/216#issuecomment-464192287 using noctua-repl on minerva-dev:
```js
r = new_request('meta', 'sparql');
r.special('query', 'CONSTRUCT {?s ?p ?o} WHERE { GRAPH gomodel:5525a0fc00000032 { ?s ?p ?o } }');
rs = new_request_set().add(r);
request_with(rs);
```
Gives me the error:
```
  _message: 'Could not successfully handle batch request. Exception: java.lang.ClassCastException. Cannot cast com.google.gson.JsonArray to com.google.gson.JsonObject',
```
from:
```
 _commentary: 'java.lang.ClassCastException: Cannot cast com.google.gson.JsonArray to com.google.gson.JsonObject\n\tat java.lang.Class.cast(Class.java:3369)\n\tat com.google.gson.Gson.fromJson(Gson.java:690)\n\tat org.geneontology.minerva.server.handler.OperationsImpl.handleSPARQLRequest(OperationsImpl.java:540)\n\tat org.geneontology.minerva.server.handler.JsonOrJsonpBatchHandler.m3Batch(JsonOrJsonpBatchHandler.java:183)\n\tat org.geneontology.minerva.server.handler.JsonOrJsonpBatchHandler.m3Batch(JsonOrJsonpBatchHandler.java:125)\n\tat org.geneontology.minerva.server.handler.JsonOrJsonpBatchHandler.m3BatchGetPrivileged(JsonOrJsonpBatchHandler.java:72)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\
```
Noting that 
```js
rs.structure()
```
which returns what is going over the wire to barista -> minerva
```json
'{"token":"wxd2t5th554jdibndx4n","intention":"action","requests":[{"entity":"meta","operation":"sparql","arguments":{"query":"CONSTRUCT {?s ?p ?o} WHERE { GRAPH gomodel:5525a0fc00000032 { ?s ?p ?o } }"}}]}'
```

**Comment by balhoff** [comment]
@kltm I just slotted it in with the previous handlers: 

https://github.com/geneontology/minerva/blob/b1849a63515954eaa672dc37c9c5ab21d628611c/minerva-server/src/main/java/org/geneontology/minerva/server/handler/JsonOrJsonpBatchHandler.java#L182-L183

Seems like it should only be seeing one request at a time.

**Comment by kltm** [comment]
@balhoff Okay, so we have `entity`: `meta`, `operation`: `sparql`; that should take use to:
https://github.com/geneontology/minerva/blob/b1849a63515954eaa672dc37c9c5ab21d628611c/minerva-server/src/main/java/org/geneontology/minerva/server/handler/OperationsImpl.java#L526
where:
`String query = request.arguments.query;` and so on, with the error occurring at:
https://github.com/geneontology/minerva/blob/b1849a63515954eaa672dc37c9c5ab21d628611c/minerva-server/src/main/java/org/geneontology/minerva/server/handler/OperationsImpl.java#L540
So, it would seem to be getting there, but the result is borked?

**Comment by kltm** [comment]
Maybe as simple as getting a list of objects instead of one?

**Comment by kltm** [comment]
@goodb Just tagging you on to this ticket as discussed today.

**Comment by kltm** [comment]
@balhoff Sorry to bother, but I've lost the curl command that you added to the Zoom chat today. IIRC, it was different from https://github.com/geneontology/minerva/issues/216#issuecomment-464192287 ? If so, could you add that again here?

**Comment by balhoff** [comment]
`curl 'http://localhost:9999/m3Batch?intention=query&requests=%5B%0A%09%7B%0A%09%22entity%22%3A%20%22meta%22%2C%0A%09%22operation%22%3A%20%22sparql%22%2C%0A%09%22arguments%22%3A%20%7B%0A%09%20%20%20%20%22query%22%3A%20%22SELECT%20DISTINCT%20%3Fs%20%3Fo%20WHERE%20%7B%20GRAPH%20gomodel%3A5525a0fc00000032%20%7B%20%3Fs%20%3Fp%20%3Fo%20%7D%20%7D%22%0A%09%09%7D%0A%09%7D%0A%5D'`

i.e.,

```
curl 'http://localhost:9999/m3Batch?intention=query&requests=[
	{
	"entity": "meta",
	"operation": "sparql",
	"arguments": {
	    "query": "SELECT DISTINCT ?s ?o WHERE { GRAPH gomodel:5525a0fc00000032 { ?s ?p ?o } }"
		}
	}
]'
```

**Comment by kltm** [comment]
Cheers! This is my problem now. I'll work back from the above until I can isolate where it goes wrong.

**Comment by kltm** [comment]
@balhoff Okay, I do the following:
```
sjcarbon@moiraine:~/local/src/git/minerva[master]$:) git pull
sjcarbon@moiraine:~/local/src/git/minerva[master]$:) ./build-cli.sh 
sjcarbon@moiraine:~/local/src/git/minerva[master]$:) java -Xmx12G -cp ../minerva/minerva-cli/bin/minerva-cli.jar org.geneontology.minerva.server.StartUpTool --use-golr-url-logging --use-request-logging --arachne -g http://purl.obolibrary.org/obo/go/extensions/go-lego.owl --set-important-relation-parent http://purl.obolibrary.org/obo/LEGOREL_0000000 --port 6800 -f /srv/tmp/blazegraph.jnl --export-folder ~/local/src/git/noctua-models/models/ --golr-labels http://noctua-golr.berkeleybop.org --golr-seed http://amigo-dev-golr.berkeleybop.org
```
in another terminal:
```
curl 'http://localhost:6800/m3Batch?intention=query&requests=%5B%0A%09%7B%0A%09%22entity%22%3A%20%22meta%22%2C%0A%09%22operation%22%3A%20%22sparql%22%2C%0A%09%22arguments%22%3A%20%7B%0A%09%20%20%20%20%22query%22%3A%20%22SELECT%20DISTINCT%20%3Fs%20%3Fo%20WHERE%20%7B%20GRAPH%20gomodel%3A5525a0fc00000032%20%7B%20%3Fs%20%3Fp%20%3Fo%20%7D%20%7D%22%0A%09%09%7D%0A%09%7D%0A%5D'
```
gives:
```
{
    "packet-id": "12c49e331eb61",
    "provided-by": [],
    "is-reasoned": false,
    "intention": "query",
    "message-type": "error",
    "message": "Could not successfully handle batch request. Exception: org.geneontology.minerva.server.handler.OperationsTools$MissingParameterException. Expected non-null value for: operation",
    "commentary": "org.geneontology.minerva.server.handler.OperationsTools$MissingParameterException: Expected non-null value for: operation
   at org.geneontology.minerva.server.handler.OperationsTools.requireNotNull(OperationsTools.java:19)
   at org.geneontology.minerva.server.handler.JsonOrJsonpBatchHandler.m3Batch(JsonOrJsonpBatchHandler.java:149)
   at org.geneontology.minerva.server.handler.JsonOrJsonpBatchHandler.m3Batch(JsonOrJsonpBatchHandler.java:132)
   at org.geneontology.minerva.server.handler.JsonOrJsonpBatchHandler.m3BatchGet(JsonOrJsonpBatchHandler.java:73)
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.lang.reflect.Method.invoke(Method.java:498)
   at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
   at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
   at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171)
   at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:195)
   at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
   at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:402)
   at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:349)
   at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:106)
   at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:259)
   at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
   at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
   at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
   at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
   at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
   at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:318)
   at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:236)
   at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1010)
   at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:373)
   at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:382)
   at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:345)
   at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:220)
   at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:547)
   at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:480)
   at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:225)
   at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:941)
   at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:409)
   at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
   at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:875)
   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
   at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:110)
   at org.eclipse.jetty.server.Server.handle(Server.java:349)
   at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:441)
   at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:919)
   at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:582)
   at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:218)
   at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:51)
   at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:586)
   at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:44)
   at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:598)
   at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:533)
   at java.lang.Thread.run(Thread.java:748)
"
}
```
I do not seem to be able to reproduce your good results...hm.

**Comment by balhoff** [comment]
@kltm what is your latest commit in your local repo?

**Comment by kltm** [comment]
commit 7ef259379f9cf5c099dedd9683f1be8cb8f04726 (HEAD -> master, origin/master, 
origin/HEAD)
Author: goodb <XXX@YYYYYY.ZZZ>
Date:   Fri May 24 08:29:01 2019 -0700

**Comment by balhoff** [comment]
@kltm that commit does not contain the SPARQL service due to a git snafu :-) I just did some rejiggering. Please update from master!

**Comment by kltm** [comment]
@balhoff Terrific--I'm now getting output that looks like it can be a starting point.

**Comment by kltm** [comment]
The following `noctua-repl` command set
```
r = new_request('meta', 'sparql')
r.special('query', 'SELECT DISTINCT ?s ?o WHERE { GRAPH gomodel:5525a0fc00000032 { ?s ?p ?o } }')
rs = new_request_set().add(r)
```
gives results like
```json
    {
     "s": {
      "type": "uri",
      "value": "gomodel:5525a0fc00000032"
     },
     "o": {
      "type": "uri",
      "value": "owl:Ontology"
     }
```
I believe we're functionally good for a first pass?

**Comment by balhoff** [comment]
Looks great.

**Comment by kltm** [comment]
A little more general, assuming the `minerva_requests` and `manager` objects:
```
var req = new minerva_requests.request('meta', 'sparql')
req.special('query', 'SELECT DISTINCT ?s ?o WHERE { GRAPH gomodel:5525a0fc00000032 { ?s ?p ?o } }')
var request_set = new minerva_requests.request_set('MYTOKEN', null);
request_set.add(req);
manager.request_with(request_set);
response.data()
```
This is now available on `noctua-dev`.

**Comment by goodb** [comment]
This is working, issue should have been closed a long time ago.  Now its being deprecated in favor of a more abstract API.
