### ISSUE TITLE
parallel model importing may not be safe

### ISSUE THREAD

**Issue by balhoff** [geneontology/minerva#432]
Currently model import uses parallel streams. I'm not sure how well we've architected the minerva code to support this. Only one can be inserted into the database at a time, anyway. Speculating that this may relate to a failure seen in the pipeline by @kltm:

```
01:18:30  skipping 568b0f9600000280.ttl
01:18:37  java.lang.ClassCastException
01:18:37  	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
01:18:37  	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
01:18:37  	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
01:18:37  	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
01:18:37  	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
01:18:37  	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
01:18:37  	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:735)
01:18:37  	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
01:18:37  	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
01:18:37  	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
01:18:37  	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
01:18:37  	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:650)
01:18:37  	at org.geneontology.minerva.cli.CommandLineInterface.importOWLModels(CommandLineInterface.java:473)
01:18:37  	at org.geneontology.minerva.cli.CommandLineInterface.main(CommandLineInterface.java:270)
01:18:37  Caused by: java.lang.ClassCastException: java.util.HashMap$Node cannot be cast to java.util.HashMap$TreeNode
01:18:37  	at java.util.HashMap$TreeNode.moveRootToFront(HashMap.java:1835)
```

**Comment by kltm** [comment]
@balhoff Do you feel that this has gotten state? Would it be fine to close this out for now, or do you still have an iron in the fire for this?

**Comment by kltm** [comment]
I'm going to vote "stale" for now.

**Comment by kltm** [comment]
@balhoff I may have hit this again today. Or something related:

```
skipping 5b91dbd100000065.ttl
skipping MGI_MGI_1917193.ttl
skipping 62900b6400000000.ttl
java.lang.ClassCastException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[...]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

The ordering of the files processed does seem to be threaded and non-deterministic. Seems pretty intermittent given that this was last poked a year and a half ago.
