### ISSUE TITLE
add a CLI command to dump all models in JSON response format

### ISSUE THREAD

**Issue by balhoff** [geneontology/minerva#500]
See https://github.com/geneontology/api-gorest-2021/issues/6#issuecomment-1181018713

@kltm is this something we should go ahead and start on?

**Comment by kltm** [comment]
Considering how we're going to use this, a tarballed version may eventually find its way into releases.

**Comment by kltm** [comment]
@balhoff Looking at the output, I think that it should be CURIEs rather than URIs to match what we're currently doing. (Re: https://github.com/geneontology/minerva/pull/501)
Otherwise, I think this may be it.

**Comment by kltm** [comment]
@balhoff Apologies to tag you here again, but I think my message above crossed when you were out. I just wanted to let you know that I tested, but we're currently using CURIEs instead of URIs for this use case (just like communicating with noctua).

**Comment by balhoff** [comment]
@kltm thanks, this was a mistake in setting up the CURIE handler. I fixed it: https://github.com/geneontology/minerva/pull/501/commits/a16995b44aeb74e7bed8f2f799736bf8c7383d9c

**Comment by kltm** [comment]
Great--thank you! I'm trying it out now.

**Comment by kltm** [comment]
@balhoff I attempted to run the full command, but it seemed to error out towards the end with:
```
2022-08-11 15:16:27,327 WARN  (com.bigdata.rdf.ServiceProviderHook:171) Running.
2022-08-11 15:16:27,327 WARN  (com.bigdata.rdf.ServiceProviderHook:171) Running.

java.lang.IllegalStateException: Manager on ontology OntologyID(OntologyIRI(<http://model.geneontology.org/MGI_MGI_1924374>) VersionIRI(<http://model.geneontology.org/MGI_MGI_1924374>)) is null; the ontology is no longer associated to a manager. Ensure the ontology is not being used after being removed from its manager.
	at uk.ac.manchester.cs.owl.owlapi.OWLImmutableOntologyImpl.getOWLOntologyManager(OWLImmutableOntologyImpl.java:202)
	at uk.ac.manchester.cs.owl.owlapi.concurrent.ConcurrentOWLOntologyImpl.withReadLock(ConcurrentOWLOntologyImpl.java:162)
	at uk.ac.manchester.cs.owl.owlapi.concurrent.ConcurrentOWLOntologyImpl.getOWLOntologyManager(ConcurrentOWLOntologyImpl.java:238)
	at org.geneontology.minerva.ModelContainer.getOWLOntologyManager(ModelContainer.java:95)
	at org.geneontology.minerva.ModelContainer.dispose(ModelContainer.java:103)
	at org.geneontology.minerva.CoreMolecularModelManager.unlinkModel(CoreMolecularModelManager.java:805)
	at org.geneontology.minerva.CoreMolecularModelManager.dispose(CoreMolecularModelManager.java:822)
	at org.geneontology.minerva.BlazegraphMolecularModelManager.dispose(BlazegraphMolecularModelManager.java:826)
	at org.geneontology.minerva.cli.CommandLineInterface.modelsToJSON(CommandLineInterface.java:530)
	at org.geneontology.minerva.cli.CommandLineInterface.main(CommandLineInterface.java:240)
```
It also seemed to be a few short of all the models
```
sjcarbon@moiraine:/tmp/jsonout$:) ls -AlF | wc -l
41940
sjcarbon@moiraine:~/local/src/git/noctua-models[master]$:( ls -AlF models/ | wc -l
42130
```
But maybe that's due to some not being capable of producing JSON for some reason?

Any thought on this error?

**Comment by balhoff** [comment]
Thanks for testing. I added parallelism to the output, since it was so slow. I'll disable this and see if it fixes the error. I suspect Minerva is not as robust to multithreading as we would like.

**Comment by kltm** [comment]
Currently testing on pipeline build machine.

**Comment by kltm** [comment]
@balhoff The output now seems in line with what I'd expect--thank you!

Noting that this took two hours on a pretty peppy machine--it might be good to explore what's going on with this as we are likely having the same issue writ small all the time in responses.

From here, we can look at adding this to the pipeline, and then onto supporting the GO-CAM API...

**Comment by kltm** [comment]
This ticket can be closed once added to the pipeline and the products are located in an accessible location for an API. https://github.com/geneontology/api-gorest-2021/issues/6

**Comment by kltm** [comment]
@balhoff IIRC, you were thinking that there might be an optimization that could be done to help accelerate the JSON dump process?

**Comment by kltm** [comment]
Okay, I think I've found a place where is parallelizes fairly well, so maybe we don't have to worry too much about speed for the moment (although this might not scale).
With that, I think we're done here--further issues can be a new ticket.
Thank you @balhoff !
