### ISSUE TITLE
Minerva cannot start up with standard ontology loads

### ISSUE THREAD

**Issue by kltm** [geneontology/minerva#77]
Initially found, with follow-up by @DoctorBud.

It seems that Minerva can no longer be started with the standard ontology loads used by either the GO or Monarch. When attempting to start minerva in various standard ways, it fails along the lines of the following:

```
2016-11-28 18:49:45,569 INFO  (ParserWrapper:69) Start loading ontology: http://purl.obolibrary.org/obo/uberon/bridge/uberon-bridge-to-emapa.owl from: http://purl.obolibrary.org/obo/uberon/bridge/uberon-bridge-to-emapa.owl
2016-11-28 18:49:45,707 INFO  (ParserWrapper:76) Finished loading ontology: null from: http://purl.obolibrary.org/obo/uberon/bridge/uberon-bridge-to-emapa.owl
2016-11-28 18:49:45,707 INFO  (ParserWrapper:76) Finished loading ontology: null from: file:/home/sjcarbon/local/src/svn/geneontology.org/trunk/ontology/extensions/go-lego.owl
Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalArgumentException: protocol = http host = null
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1488)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3018)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:489)
	at org.semanticweb.owlapi.io.AbstractOWLParser.getInputStream(AbstractOWLParser.java:103)
	at org.semanticweb.owlapi.io.AbstractOWLParser.getInputSource(AbstractOWLParser.java:232)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFXMLParser.parse(RDFXMLParser.java:72)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:197)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.actualParse(OWLOntologyManagerImpl.java:1061)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1017)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:935)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadImports(OWLOntologyManagerImpl.java:1610)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.makeLoadImportRequest(OWLOntologyManagerImpl.java:1646)
	at org.semanticweb.owlapi.functional.parser.OWLFunctionalSyntaxParser.Ontology(OWLFunctionalSyntaxParser.java:231)
	at org.semanticweb.owlapi.functional.parser.OWLFunctionalSyntaxParser.parse(OWLFunctionalSyntaxParser.java:171)
	at org.semanticweb.owlapi.functional.parser.OWLFunctionalSyntaxOWLParser.parse(OWLFunctionalSyntaxOWLParser.java:77)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:197)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.actualParse(OWLOntologyManagerImpl.java:1061)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1017)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:935)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:891)
	at owltools.io.ParserWrapper.parseOWL(ParserWrapper.java:157)
	at owltools.io.ParserWrapper.parseOWL(ParserWrapper.java:144)
	at owltools.io.ParserWrapper.parse(ParserWrapper.java:126)
	at owltools.io.ParserWrapper.parseToOWLGraph(ParserWrapper.java:117)
	at org.geneontology.minerva.server.StartUpTool.startUp(StartUpTool.java:295)
	at org.geneontology.minerva.server.StartUpTool.main(StartUpTool.java:227)
Caused by: java.lang.IllegalArgumentException: protocol = http host = null
	at sun.net.spi.DefaultProxySelector.select(DefaultProxySelector.java:176)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1132)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966)
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2701)
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2623)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1806)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	... 23 more
```

We have eliminated recent code changes (rolling back to known good versions), but are opening this here as this is where the most ontology/minerva expertise are (thinking of @cmungall and @balhoff), and the possibility that something in minerva could be done to help with the issue.

There are two guesses right now: 1) there is a typo that has somehow gotten into an ontology that both monarch and go depend on and 2) there is an unexpected consequence of our experiments in ontology deployment/redirects that occurred over the weekend.

**Comment by balhoff** [comment]
It is something messed up in the redirects:

```
jbalhoff$ curl http://purl.obolibrary.org/obo/uberon/bridge/uberon-bridge-to-emapa.owl
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="http:///ontologies.berkeleybop.org/uberon/bridge/uberon-bridge-to-emapa.owl">here</a>.</p>
<hr>
<address>Apache/2.4.7 (Ubuntu) Server at purl.obolibrary.org Port 80</address>
</body></html>
```

There is a triple slash instead of double slash in the redirect URL. If that is removed, then Protege can load `uberon-bridge-to-emapa.owl` from the resulting URL.

**Comment by kltm** [comment]
Looks like both @DoctorBud and myself were right~!

So this is probably a @cmungall question then; and possibly a product of the redirect fiddling over the holiday?

**Comment by kltm** [comment]
How long is this expected to take to percolate out? I am still unable to start Minerva.

**Comment by cmungall** [comment]
works for me:

```
curl -L http://purl.obolibrary.org/obo/uberon/bridge/uberon-bridge-to-emapa.owl
```

**Comment by cmungall** [comment]
The full import chains fails because of:

```
http://purl.obolibrary.org/obo/ddanat.owl
```

**Comment by cmungall** [comment]
Temporarily removed ddanat.owl from go-lego.owl

r37406

Should be reflected within the hour
